---
title: "titanic_prac"
output: github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r iris}
library(ggplot2)
library(titanic)
library(dplyr)
tit=titanic_train
head(tit)
```

```{r plot1, warning=FALSE}
ggplot(tit) +
  geom_point(mapping=aes(x=Age,y=Fare, color=Embarked))
```

```{r plot2}
ggplot(tit) +
  geom_point(mapping=aes(x=Age,y=Fare, size=0.2, alpha=Embarked, shape=Embarked))
```

```{r plot3}
ggplot(tit) +
  geom_point(mapping=aes(x=Age,y=Fare), color='coral')
```


```{r}
ggplot(tit) +
  geom_point(mapping=aes(x=Age,y=Fare))+
  facet_wrap(~ Pclass, nrow=3)
```

```{r}
ggplot(tit)+
  geom_point(mapping=aes(x=Age, y=Fare))+
  facet_grid(Pclass~ Embarked)
```
```{r}
ggplot(tit)+
  geom_smooth(mapping=aes(x=Age, y=Fare,linetype='line'))
```

```{r}
ggplot(tit, mapping=aes(x=Age, y=Fare))+
  geom_point(mapping=aes(color=Embarked))+
  geom_smooth(data=filter(tit, Pclass==1), se=FALSE)

##filter 조건은 dpylr 패키지가 필요함

```
```{r}
dat1<-filter(tit, Pclass==1)
head(select(dat1, Age, Pclass, Embarked))
#Age:Embarked 혹은 -로 포함하지 않음을 표현
dat2<-mutate(dat1, birth=1900 + Age)
head(arrange(dat2, Age))
#transmute는 사용되지 않은 변수를 모두 삭제한다
```

```{r}
dat_group<-group_by(tit, Pclass, Embarked)
dat2<-summarize(dat_group,
          N=n(),
          age=mean(Age, na.rm=TRUE))
ggplot(data=dat2, mapping=aes(x=N, y=age))+
  geom_point(aes(size=Pclass))
```

```{r}
dat_group<-tit %>%
  group_by(Pclass) %>%
  summarize(
          N=n() ,
          age=mean(Age, na.rm=TRUE)) %>%
ggplot(mapping=aes(x=N, y=age)) +
  geom_point(aes(color=Pclass))
```


### tidy data
```{r}
x<-tribble( ~key, ~val_x,
            1, "x1",
            2, "x2",
            3, "x3")
y<-tribble( ~key, ~val_y,
            1, "y1",
            2, "y2",
            4, "y3")
inner_join(x,y,by="key")
#semi_join, anti_join
```



