---
title: "titanic_regression"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(glmnet)
library(titanic)
library(GGally)
data<-titanic_train
head(data)
```
```{r}
ggpairs(data, columns=c(2,3,5,6))
```
```{r}
ggpairs(data, columns=c(2,8,10,12))
```

```{r}
library(corrplot)
num_data<-data[,-c(1,4,5,9,11,12)]
head(num_data)
pairs(na.omit(num_data))
corrplot(cor(na.omit(num_data)),method="number")
```
```{r}
cor.test(data$Survived, data$Pclass)
```

```{r}
cor.test(data$Survived, data$Age)
```

```{r}
num_data<-na.omit(num_data)
model1<-glm(Survived ~ Pclass+Age+SibSp+Parch+Fare, family=gaussian, data=num_data)
model_fit<-predict(model1,num_data)
summary(model1)
```

```{r}
model2<-glm(Survived ~ Pclass+Age+SibSp+Parch+Fare, family=binomial, data=num_data)
model2_fit<-predict(model2,num_data, type='response')
summary(model2)
```

```{r}
lambdas <- 10^seq(2, -3, by = -.1)
x<-as.matrix(num_data[,c(-1)])
y<-num_data$Survived
model3<-glmnet(x, y, family=gaussian, data=num_data, alpha=0)
summary(model3)
cv_ridge <- cv.glmnet(x, y, alpha = 0)
optimal_lambda <- cv_ridge$lambda.min
optimal_lambda
model3_fit <- predict(model3, s = optimal_lambda, newx = x)
```

```{r}
model4<-glmnet(x, y, family=gaussian, data=num_data, alpha=1, lambda=lambdas, standardize = TRUE)
cv_lasso <- cv.glmnet(x, y, alpha = 1, lambda = lambdas)
optimal_lambda <- cv_lasso$lambda.min
optimal_lambda
model4_fit <- predict(model4, s = optimal_lambda, newx = x)
```

```{r}
model5<-glm(Survived ~ Pclass+Age+SibSp+Parch, family=binomial, data=num_data)
model5_fit<-predict(model5,num_data, type='response')
summary(model5)
```

```{r}
num2_data<-data[,-c(1,4,9,11)]
num2_data<-na.omit(num2_data)
model6<-glm(Survived ~ factor(Sex)+Pclass+Age+SibSp+Parch+Fare+factor(Embarked), family=gaussian, data=num2_data)
model6_fit<-predict(model6,num2_data)
summary(model6)
```

```{r}
model7<-glm(Survived ~ factor(Sex)+Pclass+Age+SibSp+Parch+Fare, family=gaussian, data=num2_data)
model7_fit<-predict(model7,num2_data)
summary(model7)
```

```{r}
model8<-glm(Survived ~ factor(Sex)+Pclass+Age+SibSp+Fare, family=gaussian, data=num2_data)
model8_fit<-predict(model8,num2_data)
summary(model8)
```


```{r}

eval_results <- function(true, predicted) {
  SSE <- sum((predicted - true)^2)
  SST <- sum((true - mean(true))^2)
  R_square <- 1 - SSE / SST
  RMSE = sqrt(SSE/714)
data.frame(
  RMSE = RMSE,
  Rsquare = R_square
)
}

print(rbind(eval_results(y,model_fit),
        eval_results(y,model2_fit),
        eval_results(y,model3_fit),
        eval_results(y,model4_fit),
        eval_results(y,model5_fit),
        eval_results(y,model6_fit),
        eval_results(y,model7_fit),
        eval_results(y,model8_fit)))
```



